language: csharp
mono: latest
install:
- nuget restore JabberNet.sln
script:
- xbuild /p:Configuration=Debug JabberNet.sln
- mono ./packages/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe ./JabberNet.Test/bin/Debug/JabberNet.Test.dll
