version: 2.1.2.{build}
before_build:
- ps: ./scripts/Install.ps1
build:
    project: JabberNet.sln
after_test:
- ps: ./scripts/Package.ps1
- ps: |
    $fsi = 'C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\Fsi.exe'
    & $fsi docs\generate.fsx
